<?php

namespace ClubBundle\Repository;

/**
 * ClubMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
