<?php

namespace DepartementBundle\Repository;

/**
 * PlaningCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaningCourseRepository extends \Doctrine\ORM\EntityRepository
{
}
